nameOverride: ""
fullnameOverride: ""

minReadySeconds: 0
priorityClassName: ""

redis:
  image: redis:7.2.4
  port: 6379
  bus: 16379
  securityContext:
    enabled: false

cluster:
  init: true
  master: 3
  replicas: 1

securityContext:
  enabled: false

metrics:
  enabled: true
  image: oliver006/redis_exporter:v1.56.0
  serviceMonitor:
    enabled: true
    interval: "30s"
  securityContext:
    enabled: false

service:
  enabled: true
  type: ClusterIP

persistence:
  storage: 10Mi
  accessModes:
    - ReadWriteOnce

extraConfig:
  save: ""
  appendonly: "yes"
  cluster-node-timeout: 5000
