apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-cluster.name" . }}-config-map
  namespace: {{ .Release.Namespace | quote }}
  labels: {{ include "redis-cluster.labels" . | nindent 4 }}
data:
  redis.conf: |
    dir /data/redis
    cluster-enabled yes
    cluster-config-file nodes.conf
    port {{ .Values.redis.port }}
    cluster-port {{ .Values.redis.bus }}
    cluster-preferred-endpoint-type hostname
    {{- range $key, $value := $.Values.extraConfig }}
    {{- include "redis-cluster.addToConfig" (dict "key" $key "value" $value) | indent 4 }}
    {{- end }}
